import Head from "next/head";
import styles from "../../styles/Home.module.css";
import TestComponent from "../../components/testComponent";
import Link from "next/link";
import { getHomepage } from "./api/main";
import { NextPage } from "next";
import { readFileSync } from "fs";
import { join } from "path";

const Home: NextPage = ({ data }: any) => {
  console.log(data);

  return (
    <>
      <Head>
        <title>website_1 app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.homepage}>
        <div className="bg-red-300">website_1 App</div>
        <TestComponent />
        <div>{/* {data.map(config => RenderCard(config))} */}</div>
      </main>
    </>
  );
};
export default Home;

export async function getServerSideProps() {
  const data = await getHomepage();
  // get data locally from data.json
  // const filePath = join(process.cwd(), "data.json");
  // const fileContents = readFileSync(filePath, "utf8");
  // const data = JSON.parse(fileContents);

  return {
    props: {
      data: data,
    },
  };
}
