import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../../styles/Home.module.css";

export default function Website_2() {
  return (
    <>
      <Head>
        <title>Website_2 app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.adminpage}>Website_2 App</main>
    </>
  );
}
