import Head from "next/head";
import Script from "next/script";
import { get_Website_2_Homepage } from "../../api/main";
import { NextPage } from "next";
import { RenderComponents } from "@/utils/RenderComponents";
import Header from "../../components/Header";
const Home: NextPage = ({ data }: any) => {
  console.log(data);

  return (
    <>
      <Head>
        <title>website-2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* scripts are loaded with minimal impact to page performance. */}
      {/* <Script src="https://cdn.tailwindcss.com" /> */}
      <script src="https://cdn.tailwindcss.com" defer></script>

      <main className="website-1">
        <Header logo="Website_2" />
        {data &&
          data.map((value: any, key: number) => (
            <section key={key}>
              {RenderComponents(value.component, value.id)}
            </section>
          ))}
      </main>
    </>
  );
};
export default Home;

export async function getServerSideProps() {
  const data = await get_Website_2_Homepage();

  return {
    props: {
      data: data,
    },
  };
}
